### ISSUE TITLE
Finalize name

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrology#11]
Options are:
-Hydrology and meteorology
-Water (or water science)
-Hydroscience

I think my final vote is 'water science', as it encompasses hydrology, meteorology, and ecology - all of which are represented in the packages we include - but is also not so specific so if a meteorology task view gets spun off later, we wouldn't have to rename.

@ilapros @boshek - final votes?

**Comment by ilapros** [comment]
I like "water Sciences" but not sure if Achim was very much in favour if that. MY second favourite would be Hydroscience.

**Comment by boshek** [comment]
👍 to water science. My concern with hydroscience is that it is too specific and prescriptive. Plus it is the name of a bunch of companies.

**Comment by szipper** [comment]
OK, let's go with Water Science then. I think it's the most appropriate name, and we all like it, so let's lock it in

@boshek Is it possible to rename the repository and all the input files from `hydrometeorology.*` to `waterscience.*` and change the GitHub URL? I didn't want to break anything but I think that would help minimize confusion down the road...

**Comment by boshek** [comment]
it is definitely possible. I think we should confirm with Achim first?

**Comment by boshek** [comment]
I am having a little trouble finding a definition of water science and am now wondering if just *hydrology* is not more appropriate.

Here is the [wikipedia](https://en.wikipedia.org/wiki/Hydrology) definition of hydrology:
> Hydrology (from Greek: ὕδωρ, "hýdōr" meaning "water"; and λόγος, "lógos" meaning "study") is the scientific study of the movement, distribution, and quality of water on Earth and other planets, including the water cycle, water resources and environmental watershed sustainability.

And from the [USGS](https://water.usgs.gov/edu/hydrology.html):
> Hydrology is the science that encompasses the occurrence, distribution, movement and properties of the waters of the earth and their relationship with the environment within each phase of the hydrologic cycle.

My working definition of water science is entirely encompassed by the hydrology definition and hydrology has the advantage of being something people recognize. Hydrology contains all sorts of sub-disciplines allowing us the flexibility of including a range of packages while keeping familiar terminology. Realistically I think more people will find a hydrology task view if they have a water related problem they want to solve with R than with water science. 

Sorry to flip flop on this.

**Comment by boshek** [comment]
Not just *Hydrology*?

**Comment by szipper** [comment]
Sure - let's do it! I don't know anything about meteorology, anyways

**Comment by boshek** [comment]
@szipper @ilapros Updated our url. Probably best to change your remotes.
