### ISSUE TITLE
Add <info> to <links>

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrology#16]
From Achim: 

> The `<info>` text highlights links to various useful resources on the web
> (e.g., Riccardo Rigon's page, ROpenSci MapTools Listing, RHydro project,
> etc.). It would be useful to also include these in the `<links>` section.

**Comment by ilapros** [comment]
Added the links I considered worthy to be added in fa3554e  - maybe more needed?

**Comment by boshek** [comment]
I think this looks great.
