### ISSUE TITLE
Distinguish between CRAN and GitHub packages

### ISSUE THREAD

**Issue by szipper** [ropensci/hydrology#19]
From Achim:

> The current version of the task view does not distinguish very clearly
> between CRAN and GitHub packages. So users might be confused that
> `available.views()` and `install.views()` etc. do not get them all packages.
> Other task views address this by adding a note such as "on GitHub" or so
> when non-CRAN packages are listed in the `<info>` section.

**Comment by ilapros** [comment]
Added "GitHub only package" comment for the Github packages (and checked they didn't exist in CRAN) 
fa3554e

**Comment by szipper** [comment]
Also added one comment for an R-Forge package in 66cf79c
