### ISSUE TITLE
Make makefile safe for windows

### ISSUE THREAD

**Issue by rabutler-usbr** [ropensci/Hydrology#31]
When I was working on adding prism, the makefile would not work for me initially. 

The error related to the quotes used in the call to R, e.g., `install.packages("ctv", repos = "http://cran.rstudio.com/")`. 

I was able to fix this by replacing all of the calls to `R` with calls to `Rscript`. 

I *think* this is a windows issue, but maybe my quick research didn't quite fully explain the issue. 

If you are not using windows, could you confirm that it will work for you with `Rscript`, and if it does, consider switching to it? Or maybe there are other reasons to stick with `R` over `Rscript`?

**Comment by boshek** [comment]
@rabutler-usbr as another solution to this problem I am now just using github actions to process the `Hydrology.md` file. Runs automatically and [generates](https://github.com/ropensci/Hydrology/blob/master/.github/workflows/make-ctv-file.yaml) the ctv file on pushes and pull requests. You can monitor its progress [here](https://github.com/ropensci/Hydrology/actions) whenever you push or a pull request is created. cc @samzipper & @ilapros

**Comment by rabutler-usbr** [comment]
Awesome, sound even better. Thanks for following up.
