### ISSUE TITLE
nhdR package

### ISSUE THREAD

**Issue by jsta** [ropensci/Hydrology#34]
> Package newly added to CRAN

**package name:** nhdR
**repository:** https://github.com/jsta/nhdR
**development URL:** https://github.com/jsta/nhdR
**description/detail:** Tools for working with the National Hydrography Dataset, with functions for querying, downloading, and networking both the NHD <https://www.usgs.gov/core-science-systems/ngp/national-hydrography> and NHDPlus <http://www.horizon-systems.com/nhdplus> datasets.

**Comment by boshek** [comment]
Closed via #35
