### ISSUE TITLE
smapr package

### ISSUE THREAD

**Issue by samzipper** [ropensci/Hydrology#39]
Package name: smapr: Acquisition and Processing of NASA Soil Moisture Active-Passive (SMAP) Data
CRAN: https://cran.r-project.org/web/packages/smapr/index.html
Repository: https://github.com/ropensci/smapr
Description/detail: Facilitates programmatic access to NASA Soil Moisture Active Passive (SMAP) data with R. It includes functions to search for, acquire, and extract SMAP data.

**Comment by boshek** [comment]
😈 - already in there
