### ISSUE TITLE
CDECRetrieve package 

### ISSUE THREAD

**Issue by ergz** [ropensci/Hydrology#40]
add: CDECRetrieve 
CRAN: https://cran.r-project.org/package=CDECRetrieve
Github: https://github.com/FlowWest/CDECRetrieve
Description: CDEC maintains a set of web services at <http://cdec.water.ca.gov/queryTools.html>. In order to better interact and analyze the data this R packages allows users to quickly and easily retrieve data.

**Comment by boshek** [comment]
Happy to include this once it is back on CRAN. Do you know what the policy violation was?
