### ISSUE TITLE
somspace package

### ISSUE THREAD

**Issue by imarkonis** [ropensci/Hydrology#44]
Package to add: somspace
CRAN: https://cran.r-project.org/package=somspace
Github: https://github.com/imarkonis/somspace
Vignette: https://imarkonis.github.io/somspace/
Description: Application of the Self-Organizing Maps technique for spatial classification of time series. The package uses spatial data, point or gridded, to create clusters with similar characteristics. The clusters can be further refined to a smaller number of regions by hierarchical clustering and their spatial dependencies can be presented as complex networks. Thus, meaningful maps can be created, representing the regional heterogeneity of a single variable. In the vignette, spatial classification of European Palmer Drought Severity index is presented.

**Comment by boshek** [comment]
This looks like a really interesting package!

**Comment by imarkonis** [comment]
Thanks Sam, it is really great to see people so active in hydrologic/climatic implementations in R like you :)

**Comment by boshek** [comment]
Should be up on CRAN in the next few days.
