### ISSUE TITLE
Packages that have been archived on CRAN

### ISSUE THREAD

**Issue by boshek** [ropensci/Hydrology#45]
@samzipper @ilapros 

What do you think the best approach to deal with packages that were previously on CRAN but then have been removed for policy violations. For example: https://cran.r-project.org/web/packages/sbtools/index.html

My suggestion is to leave them in the hydrology task view for six months. They show up in the `check_ctv_packages` step in our process. If after six months the problem still hasn't been resolved, we remove them from the task view. Thoughts?

**Comment by samzipper** [comment]
That seems like a reasonable standard to me... 6 months should be long enough for people to get their acts together.

Speaking of which, how often do we submit an update to CRAN? Or is that automagically happening through GitHub/rOpenSci somehow?

**Comment by boshek** [comment]
No automagic with that step though really it is pretty minimal. I received write access to this [repo](https://r-forge.r-project.org/projects/ctv) from Achim so every few changes I commit the changes there. It is pretty painless.

**Comment by ilapros** [comment]
agree with the proposed approach. And I would extend it to packages archived for any reason or orphaned.
