### ISSUE TITLE
Add nasapower?

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/Hydrology#46]
I'm wondering if nasapower isn't a good fit for this CTV as well for the daily meteorology it provides?

package name: nasapower
repository: https://github.com/ropensci/nasapower
description/detail from DESCRIPTION:
	
	Client for 'NASA' 'POWER' global meteorology, surface solar
    energy and climatology data 'API'.  'POWER' (Prediction Of Worldwide Energy
    Resource) data are freely available global meteorology and surface solar
    energy climatology data for download with a resolution of 1/2 by 1/2 arc
    degree longitude and latitude and are funded through the 'NASA' Earth
    Science Directorate Applied Science Program.  For more on the data
    themselves, a web-based data viewer and web access, please see <https://power.larc.nasa.gov/>.

**Comment by boshek** [comment]
Without a doubt. You can either add it via a PR, modifying [this file](https://github.com/ropensci/Hydrology/blob/master/Hydrology.md) or I can do it further down the road.

**Comment by adamhsparks** [comment]
Cool, thanks. I've made a PR. https://github.com/ropensci/Hydrology/pull/47
