### ISSUE TITLE
Include FedData package?

### ISSUE THREAD

**Issue by tungmilan** [ropensci/Hydrology#50]
Please consider adding this very useful [FedData](https://github.com/ropensci/FedData) package. 

This is the information provided on its GitHub page

Functions to Automate Downloading Geospatial Data Available from Several Federated Data Sources. The package enables extraction from seven datasets: 

* The [National Elevation Dataset (NED)](http://ned.usgs.gov) digital elevation models (1 and 1/3 arc-second; USGS)
* The [National Hydrography Dataset (NHD)](http://nhd.usgs.gov) (USGS)
* The [Soil Survey Geographic (SSURGO) database](http://websoilsurvey.sc.egov.usda.gov/) from the National Cooperative Soil Survey (NCSS), which is led by the Natural Resources Conservation Service (NRCS) under the USDA
* The [Global Historical Climatology Network (GHCN)](http://www.ncdc.noaa.gov/data-access/land-based-station-data/land-based-datasets/global-historical-climatology-network-ghcn), coordinated by National Climatic Data Center at NOAA
* The [Daymet](https://daymet.ornl.gov/) gridded estimates of daily weather parameters for North America, version 3, available from the Oak Ridge National Laboratory's Distributed Active Archive Center (DAAC)
* The [International Tree Ring Data Bank (ITRDB)](http://www.ncdc.noaa.gov/data-access/paleoclimatology-data/datasets/tree-ring), coordinated by National Climatic Data Center at NOAA
* The [National Land Cover Database (NLCD)](https://www.mrlc.gov/) from 2011, 2006, and 2001

**Comment by boshek** [comment]
Oh without a doubt this belong here.
