### ISSUE TITLE
Adding openair package?

### ISSUE THREAD

**Issue by tungmilan** [ropensci/Hydrology#51]
Hello,

Please consider adding the [openair](https://github.com/davidcarslaw/openair) package too.

This is the information provided on its GitHub page:

**openair** is an R package developed for the purpose of analysing air
quality data — or more generally atmospheric composition data. 

This package continues to develop and input from other developers would
be welcome. A summary of some of the features are:

  - **Access to data** from several hundred UK air pollution monitoring
    sites through the `importAURN` and `importKCL` functions.
  - **Utility functions** such as `timeAverage` and `selectByDate` to
    make it easier to manipulate atmospheric composition data.
  - Flexible **wind and pollution roses** through `windRose` and
    `pollutionRose`.
  - Flexible plot conditioning to easily plot data by hour or the day,
    day of the week, season etc. through the openair `type` option
    available in most functions.
  - More sophisticated **bivariate polar plots** and conditional
    probability functions to help characterise different sources of
    pollution. A paper on the latter is available
    [here](http://www.sciencedirect.com/science/article/pii/S1364815214001339).
  - Access to NOAA [Hysplit](http://ready.arl.noaa.gov/HYSPLIT.php)
    pre-calculated annual 96-hour back **trajectories** and many
    plotting and analysis functions e.g. trajectory frequencies,
    Potential Source Contribution Function and trajectory clustering.
  - Many functions for air quality **model evaluation** using the
    flexible methods described above e.g. the `type` option to easily
    evaluate models by season, hour of the day etc. These include key
    model statistics, Taylor Diagram, Conditional Quantile plots.

![](http://davidcarslaw.github.io/openair/reference/timeVariation-1.png)

![](http://davidcarslaw.github.io/openair/reference/windRose-3.png)

**Comment by boshek** [comment]
@samzipper @ilapros I feel like this fits in the task view?

**Comment by samzipper** [comment]
Strong agree! Maybe in both the data retrieval and data analysis sections for met data? Looks like a great package!
