### ISSUE TITLE
Package baseflow

### ISSUE THREAD

**Issue by Tagar95** [ropensci/Hydrology#55]
Hello,

I am the maintainer of the package baseflow, which is now on [CRAN](https://cran.r-project.org/package=baseflow). Source code is available [here](https://gitlab.irstea.fr/HYCAR-Hydro/baseflow). Could you consider adding it to the list ?

It is a hydrograph analysis package that implements a hydrograph separation method detailed in an [article](https://www.hydrol-earth-syst-sci-discuss.net/hess-2019-503/), which is under review in HESS : Pelletier, A. and Andréassian, V.: Hydrograph separation: an impartial parametrization for an imperfect method, Hydrol. Earth Syst. Sci. Discuss., https://doi.org/10.5194/hess-2019-503, in review, 2019.

Thank you in advance.

**Comment by boshek** [comment]
Absolutely! Looks like a great contribution.
