### ISSUE TITLE
Many emails with little information for users who watch this package

### ISSUE THREAD

**Issue by wenlong-liu** [ropensci/Hydrology#59]
To whom it may concern,

As an R user working with hydrology, I am really interested in the topic and this repo.  I would like to express my appreciation to the developer and maintainers for their time and effort.

I understand the developer and maintainers were trying to test and implement some new features in this package.  However, at your convenience, would you please check the reason why many notifications with little information were pushed via email? Around 12 emails with the topic of _trying to automate with gh-actions (#57)_ .

Thank you again for your excellent work.  

Best,
Wenlong

**Comment by boshek** [comment]
Hi there - that would a notification issue with your settings for GitHub. If you set your notifications to not have GitHub send you emails, this should fix the problem on your end.

**Comment by wenlong-liu** [comment]
Thanks for your reply. I have already updated the notification setting.  

Best,
Wenlong

**Comment by boshek** [comment]
👋  @wenlong-liu Sorry just a little follow-up. 

> I have already updated the notification setting.

Does that mean you are getting notification emails despite having settings to not receive them?

**Comment by wenlong-liu** [comment]
Sorry for the late response. After I change the settings, I did not receive the emails.  I only get email notification when I was mentioned.  Thank you.
