### ISSUE TITLE
update fasstr reference - now on CRAN

### ISSUE THREAD

**Issue by jongoetz** [ropensci/Hydrology#63]
The fasstr package listed under 'Data Analysis' is now a CRAN package (https://CRAN.R-project.org/package=fasstr). As fasstr functions complete more than just data tidying (various flow statistics, trends and other analyses are included), I would recommend placing it in the 'Hydrograph analysis' section. Thanks!

**Comment by boshek** [comment]
Automated process did not work and fasstr still points to github page.
