### ISSUE TITLE
Add packages

### ISSUE THREAD

**Issue by zejiang-unsw** [ropensci/Hydrology#99]
I would like to incorporate the following packages to the task view:

WASP:
https://cran.irsn.fr/web/packages/WASP/index.html
https://github.com/zejiang-unsw/WASP

NPRED:
https://cran.csiro.au/web/packages/NPRED/index.html
https://github.com/zejiang-unsw/NPRED

**Comment by zejiang-unsw** [comment]
> I would like to incorporate the following packages to the task view:
> 
> WASP: https://cran.irsn.fr/web/packages/WASP/index.html https://github.com/zejiang-unsw/WASP
> 
> NPRED: https://cran.csiro.au/web/packages/NPRED/index.html https://github.com/zejiang-unsw/NPRED

Any update?

**Comment by boshek** [comment]
Closed via #100
